name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v2

      - name: Build (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          zig build -Doptimize=ReleaseFast -Dno-fileselector -fno-sys=libxkbcommon -Dxkb-config-root="" -Dx-locale-root=""
          zig build -Doptimize=ReleaseFast -Dno-fileselector -Dlegacy

      - name: Build (macOS)
        if: matrix.os == 'macos-latest'
        run: zig build -Doptimize=ReleaseFast -Dno-fileselector

      - name: Build (windows)
        if: matrix.os == 'windows-latest'
        run: zig build -Doptimize=ReleaseFast

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: zig-out
